### ISSUE TITLE
Font family & font stack stats

### ISSUE THREAD

**Issue by LeaVerou** [LeaVerou/css-almanac#15]
Try to detect and show numbers for the native font stack variations, compared to the other popular font families like Open Sans and Roboto.

([by @catalinred](https://github.com/HTTPArchive/almanac.httparchive.org/issues/898#issuecomment-653429755))

**Comment by catalinred** [comment]
Here are two of the most popular CSS font stacks in the wild:

- GitHub's:
`font-family: -apple-system,BlinkMacSystemFont,Segoe UI,Helvetica,Arial,sans-serif,Apple Color Emoji,Segoe UI Emoji;`

- Bootstrap's:
  `font-family: -apple-system,BlinkMacSystemFont,"Segoe UI",Roboto,"Helvetica Neue",Arial,"Noto Sans",sans-serif,"Apple Color Emoji","Segoe UI Emoji","Segoe UI Symbol","Noto Color Emoji";`

Besides having slight variations, the common thing here is the usage of:
`apple-system, BlinkMacSystemFont, Segoe UI, Arial, Apple Color Emoji, sans-serif`

So I'm guessing here that if we find a `font-family` declaration with a value that contains the string above - more or less -  then we have a native font stack to count.

Hope this helps.

**Comment by Crissov** [comment]
Iʼd also be interested in common font stacks for scripts other than Latin / Greek / Cyrillic, put in comparison to the downloadable fonts used.

**Comment by LeaVerou** [comment]
Since font stacks are often copied and pasted, and their popularity is essentially a proxy for the popularity of the tools they come from, it may be more illuminating to measure **font** stats.

**Comment by LeaVerou** [comment]
So, to measure font family stats, we'd look at `font-family` and `font` (extract the part after any numbers, if any numbers are present), split by commas, trim spaces and quotes, then combine.

We don't want to measure usage within the website, because that reflects more on the structure of the stylesheet (how often you can't inherit and need to repeat the font stack) than actual importance of the font. We do however want to keep track of the (average) index in the font stack, then aggregate this over the website corpus.

**Comment by Crissov** [comment]
Would it also be interesting and helpful to collect stats on the usage of quoted strings vs. unquoted identifiers, especially for font names with spaces or non-ASCII letters?

**Comment by LeaVerou** [comment]
After consulting with @rviscomi, it appears the overlap with the Fonts chapter is too significant, so we will not have a Fonts section. Therefore, I'm closing this.
