### ISSUE TITLE
font-variant-*

### ISSUE THREAD

**Issue by svgeesus** [LeaVerou/css-almanac#23]
Stats on which `font-variant-*` longhands  such as [`font-variant-numeric`](https://drafts.csswg.org/css-fonts-4/#font-variant-numeric-prop) or  [`font-variant-east-asian`](https://drafts.csswg.org/css-fonts-4/#font-variant-east-asian-prop) are being used. 

Also whether the [`font-variant` shorthand](https://drafts.csswg.org/css-fonts-4/#font-variant-prop) is being used with the [`none`](https://drafts.csswg.org/css-fonts-4/#font-variant-none-value) value, to reset all the longhands.

**Comment by Crissov** [comment]
Comparative stat for `font-feature-settings`?

**Comment by svgeesus** [comment]
> Comparative stat for `font-feature-settings`?

Indeed, that would be very useful, particularly where one could use either approach. IIRC `font-feature-settings` was deployed in browsers first, so some usage may simply reflect "that was the only thing that worked at the time".

CSS Fonts 4 has the data to map feature codes to variant values.

**Comment by svgeesus** [comment]
**Correspondences between high-level `font-*` properties and low-level `font-feature-settings` features**

[font-kerning](https://drafts.csswg.org/css-fonts-4/#font-kerning-prop)

- `kern`
- `vkrn`

[font-variant-ligatures](https://drafts.csswg.org/css-fonts-4/#font-variant-ligatures-prop)

- `liga`
- `clig`
- `dlig`
- `hlig`
- `calt`

[font-variant-position](https://drafts.csswg.org/css-fonts-4/#font-variant-position-prop)

Perhaps check if stylesheet authors try to nest this (it doesn't work)

- `subs`
- `sups`

[font-variant-caps](https://drafts.csswg.org/css-fonts-4/#font-variant-caps-prop)

Also depends on value of [font-feature-settings](https://drafts.csswg.org/css-fonts-4/#propdef-font-feature-settings)

- `smcp`
- `c2sc`
- `pcap`
- `c2pc`
- `unic`
- `titl`

[font-variant-numeric](https://drafts.csswg.org/css-fonts-4/#font-variant-numeric-prop)

- `lnum`
- `onum`
- `pnum`
- `tnum`
- `frac`
- `afrc`
- `ordn`
- `zero`

[font-variant-alternates](https://drafts.csswg.org/css-fonts-4/#font-variant-alternates-prop)

This one was dropped from CSS Fonts 3 due to lack of implementer support. This is an area where the Open Web Platform lags behind native, which has good alternates support.

- `hist`
- `salt`
- `ssxx` where _xx_ is 00 to 20
- `cvxx` where _xx_ is 00 to 99
- `swsh`
- `cswh`
- `ornm`
- `nalt`

[font-variant-east-asian](https://drafts.csswg.org/css-fonts-4/#font-variant-east-asian-prop)

- `jp78`
- `jp83`
- `jp90`
- `jp04`
- `smpl`
- `trad`
- `fwid`
- `pwid`
- `ruby`

**Comment by LeaVerou** [comment]
Alright, so this again seems pretty straightforward:

1. We measure usage of the various `font-variant` properties, including usage in the `font-variant` shorthand and the `font` shorthand. We should probably keep the counts separate, to see if the shorthands are used at all (or we can just do that in #10 and not care about it here)
2. We measure usage of [the various low-level settings @svgeesus posted about](https://github.com/LeaVerou/css-almanac/issues/23#issuecomment-663855378) by measuring incidence of the code in quotes in `font-feature-settings` (single or double quotes).

**Comment by LeaVerou** [comment]
After consulting with @rviscomi, it appears the overlap with the Fonts chapter is too significant, so we will not have a Fonts section. Therefore, I'm closing this.
