### ISSUE TITLE
What percentage of CSS is served minified?

### ISSUE THREAD

**Issue by LeaVerou** [LeaVerou/css-almanac#25]
…and what percentage of that uses sourcemaps?

**Comment by LeaVerou** [comment]
Damn, this would have been very easy to measure with the custom metrics code for #39. Anyhow, now we will need to match the HTML for `.min.css` in `<link rel=stylesheet”>`. Not sure how HTML querying works, does it need to be in the raw body or is there a parsed DOM stored similar to our Rework AST for CSS? @rviscomi ?

An alternative plan would be to match the CSS itself for patterns that are common in minified files, eg no comments, no spacing between tokens that can avoid it, all declarations on the same line etc. That’s probably more accurate but more involved to code.

**Comment by rviscomi** [comment]
Since this metric missed the custom metric window would you be open to cutting it from the chapter? Querying the response bodies is prohibitively expensive and the remaining heuristics may not be strong enough to answer this question confidently.
