### ISSUE TITLE
What CSS hacks are still used to target browsers/versions/platforms？

### ISSUE THREAD

**Issue by bradkemper** [LeaVerou/css-almanac#40]
Are authors still using these？Which ones are most prevalent that work with common versions of browsers? If possible to determine, which problems are being solved that can’t be solved with \@supports?

For reference: http://browserhacks.com/

**Comment by LeaVerou** [comment]
Ok, this highlights a distinction that I believe is generally important for the Almanac. 
Is "still used" here implying usage in stylesheets written or edited in 2019-2020? Or just stylesheets *served* in that time period?
And if the former, can we make that distinction? @rviscomi?

**Comment by LeaVerou** [comment]
Apart from that, we need to narrow down the list of hacks that a) we _want_ to measure and b) we *can* measure

**Comment by bradkemper** [comment]
Maybe both, separately, but the most recent couple of years especially. 

Personally, I'm not interested in those that target IE < 11. I am interested in those that target IE11, those that differentiate between IE and Edge and Chromium Edge (if such yet exist), and those that are used in versions of Safari, Firefox, and Chrome that are post-@-supports.

**Comment by rviscomi** [comment]
@LeaVerou there may be heuristics to reason about a stylesheet's freshness like `Last-Modified` or the presence of the resource in an earlier crawl, but I wouldn't rely on those for any meaningful conclusions. I think serving the resource _today_ itself is a meaningful signal and the chapter can discuss possible explanations like staleness/hackyness as needed without necessarily having to prove which it is.

**Comment by LeaVerou** [comment]
I'm afraid we need to let this one go in favor of the other metrics. 

* We're running late, and this doesn't even have a clear algorithm yet of what we're measuring and how, only a URL. It would be a tremendous effort to measure *all* hacks in that URL. 
* Most importantly, many of them are not even parseable by Rework, making analysis impossible. If we restrict analysis to those which are valid CSS, then the statistic becomes less interesting, while still being very time consuming to calculate.
